name: Dump

on:
  push:
    branches:
      - master

env:
  DUMP_URL: "https://master.dl.sourceforge.net/project/fihsw-msm8937/D1C/FIHSW_D1C-5210-0-00WW-B03_600WW_8.0.0_20180101.full.lzma2.a2fdbbe2f9480671eb82aa116346c9c196899a2cfd663e013c1c44cc4747be52.7z?viasf=1" # Direct url to a recovery zip

jobs:
  dump:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          overprovision-lvm: true
          remove-dotnet: true
          remove-android: true
          remove-codeql: true
          remove-haskell: true
          remove-docker-images: true

      - name: Set up Git
        uses: actions/checkout@v3

      - name: Create .githubtoken file
        run: echo "${{ secrets.GIT_TOKEN }}" > .githubtoken

      - name: Create .tgtoken file
        run: echo "${{ secrets.TELEGRAM_TOKEN }}" > .tgtoken

      - name: Set up environment
        run: bash setup.sh

      # protobuf-compiler is required for this
      #- name: Install otadump
      #  uses: actions-rs/install@v0.1
      #  with:
      #    crate: otadump
      #    version: latest

      - name: Run dumpyara
        run: |
          if [[ $DUMP_URL == *"pixeldrain"* || $DUMP_URL == *"dlcdnets.asus.com"* ]]; then
            wget -O dump.zip "$DUMP_URL"
            bash dumpyara.sh dump.zip
          else
            bash dumpyara.sh "https://cdn-ota.azureedge.net/V14.0.13.0.TKOCNXM/lisa_images_V14.0.13.0.TKOCNXM_20231110.0000.00_13.0_cn_chinatelecom_4674d311c6.tgz"
          fi
